name: Publish

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq cloc

      - name: Generate report
        run: |
          ./produce-report.sh
          mkdir -p dist
          cp index.html report.tsv dist/

      - name: Publish coverage report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
